### ISSUE TITLE
Version 3.0.0 and 3.1.0 generate cyclic method calling in the new version of XCode 10.2

### ISSUE THREAD

**Issue by fiteroc** [JohnSundell/Unbox#241]
The problem occurs after converting a project to Swift 5 and the cyclic method calling occurs with this method which appears to call upon itself:

    public func unbox<T: UnboxCompatible>(key: String) -> T? {
        return try? self.unbox(key: key)
    }

Also the version 3.1.0 is not available on Cocoapods. Please check that out as well. Thanks!

**Comment by ZeroOnet** [comment]
I also meet this problem because of try?. In Swift 5 mode, try? is modified:
> In Swift 5 mode, try? with an expression of an Optional type flattens the resulting optional, instead of returning a nested optional. (SE-0230) (47313584)

**Comment by pbeo** [comment]
I fixed it here #242

**Comment by fiteroc** [comment]
The fix is good. Thanks! Waiting for new version!

**Comment by eliburke** [comment]
I still get warnings even using @pbeo 's fix branch. 

````
var horizontalAccuracy: Double = -1.0
self.horizontalAccuracy = try? unboxer.unbox(key: "horizontal_accuracy")
````
Produces an error: "Ambiguous reference to member 'unbox(key:)'"

````
self.horizontalAccuracy = (try? unboxer.unbox(key: "horizontal_accuracy")) ?? -1.0
````
Produces the warning: "No calls to throwing functions occur within 'try' expression"

````
if let horizontalAccuracy: Double = try? unboxer.unbox(key: "horizontal_accuracy") {
    self.horizontalAccuracy = horizontalAccuracy
}
````
Produces the warning: "No calls to throwing functions occur within 'try' expression"

Can this be fixed within Unbox or do I now need to wrap this type of construct in _do ... catch_ blocks? (I want my structs to contain non-optional properties-- the JSON is optional)

**Comment by eliburke** [comment]
Well.. I'm glad I spent 10 minutes writing that message. @JohnSundell 's Swift5 update addresses my various issues (after some frenzied refactoring)

Thanks @JohnSundell !

**Comment by JohnSundell** [comment]
No worries, happy to help! 🙂 Closing this now since it's fixed both on `master` and version `4.0.0`, containing the fix, has been released on CocoaPods. Thanks everyone 👍

**Comment by ZeroOnet** [comment]
> No worries, happy to help! 🙂 Closing this now since it's fixed both on `master` and version `4.0.0`, containing the fix, has been released on CocoaPods. Thanks everyone 👍

Thanks!
